version: '3'
services:
  postgres:
    image: postgres
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: url-shortener-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  go-api:
    build:
      context: .
    container_name: url-shortener-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: url-shortener-db
